messages:
  UseCmd: '&d&l** &d%player% &fиспользовал(а) команду - &d%command%' #Сообщение об использовании команды
  ConsoleOn: '&d&l** &fРежим консоли - &aвключён' #Консоль включена
  ConsoleOff: '&d&l** &fРежим консоли - &cвыключён' #Консоль выключена
ignore:
- '/l'
- '/login'
- '/reg'
- '/register'
- '/changepassword'
- '/email'
