messages:
  UseCmd: '&d&l>> &a%player% &fИспользовал команду - &c%command% &d&l<<' #Сообщение при использовании команды игрока
  ConsoleOn: '&d&l>> &fКонсоль - &aВключена &d&l<<' #Сообщение при включении консоли
  ConsoleOff: '&d&l>> &fКонсоль - &cВыключена &d&l<<' #Сообщение при выключении консоли
  ReloadCmd: '&d&l>> &eПлагин успешно перезагружен! &d&l<<' #Сообщение при перезагрузке плагина
ignore:
- '/l'
- '/login'
- '/reg'
- '/register'
- '/changepassword'
- '/email'
